name = "express-example"
main = "index.js"
compatibility_date = "2025-07-30"
compatibility_flags = [
  "nodejs_compat",
  "enable_nodejs_http_modules",
  "enable_nodejs_http_server_modules",
  "enable_nodejs_os_module",
  "enable_nodejs_process_v2",
  "experimental",
]